### PR TITLE
Callback needs to be to `localhost`

### PR DESCRIPTION
**Pull request by dbrnz**
This maybe OS/X specific, but OAuth1 fails with "No oauth_token, oauth_token_secret or oauth_callback_confirmed in response" if callback is to `127.0.0.1`.

### CODE REVIEW

**Comment by pipacs** [comment]
What service triggers this? I'm also on OSX, but haven't experienced the problem so far.

**Comment by dbrnz** [comment]
This is with https://models.physiomeproject.org

**Comment by dbrnz** [comment]
I've reworked this to leave the default value unchanged and instead allowed the user to override the callback URL.

**Comment by pipacs** [comment]
Looking great but can't be merged -- please update.

**Comment by dbrnz** [comment]
This should now be fine.

**Pull request merged**
