### PR TITLE
Tidy up TimedReply for OAuth1.

### PR DESCRIPTION
**Pull request by dbrnz**
I wanted to remove `#include "o1requestor.moc"` from `o1requestor.cpp` and also:
```
connect(this, SIGNAL(error(QNetworkReply::NetworkError)), parent, SIGNAL(error(QNetworkReply::NetworkError)));
```
looked dubious -- hopefully this is an improvement.

### CODE REVIEW

**Comment by pipacs** [comment]
Thanks, but TimedReply is an internal class, I see no reason to publish it. Forwarding the error signal is important as well.

**Comment by dbrnz** [comment]
OK, I'm happy with the code (I hadn't looked close enough before...). However, when using it as part of a larger project and building with CMake, the `#include "o1requestor.moc"` stops the build as the file cannot be found -- with `TimedReply` in `o1requestor.h` (and renamed) all is well.

Would you accept a PR putting `TimedReply` into the header file??

Thanks.

**Comment by pipacs** [comment]
Sure, if this help CMake, let's do it. Two things though:

- Have you tried with ATOMOC? https://cmake.org/cmake/help/v3.0/prop_tgt/AUTOMOC.html
- If that doesn't help, could you publish it as O1TimedReply in O1TimedReply.h|cpp

**Comment by dbrnz** [comment]
I'm back onto this after other commitments...

AUTOMOC doesn't help so have created `o1timedreply.h` and `.cpp`.

**Pull request merged**
